apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-k8s
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: alpine:3.18
        command:
          - sh
          - -c
          - |
            echo "Running permission fix..."
            chown -R 1000:1000 /var/jenkins_home || true
            chmod -R 755 /var/jenkins_home || true
        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc
