apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.6
    path: /srv/nfs/jenkins
