apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.6       # e.g., 192.168.56.2
    path: /srv/nfs/maven-cache
